# Generated by Django 4.1.13 on 2024-06-02 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voice', models.BooleanField(verbose_name='YES/NO')),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Voice',
                'verbose_name_plural': 'Voices',
            },
        ),
    ]
